// Generated by CoffeeScript 1.3.3
(function() {
  var FAPI_FILES_ROOT, allowCrossDomain, app, config, express, fapi, port;

  express = require('express');

  fapi = new require(process.env.FAPI_ROOT || './fapi');

  app = express.createServer(express.logger());

  config = {
    allowedDomains: '*'
  };

  allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', config.allowedDomains);
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST');
    res.header('Access-Control-Allow-Headers', 'Content-Type');
    return next();
  };

  app.configure(function() {
    app.use(express.bodyParser());
    app.use(express.cookieParser());
    app.use(express.methodOverride());
    app.use(allowCrossDomain);
    return app.use(app.router);
  });

  FAPI_FILES_ROOT = 'fake_plugins';

  app.get(/^\/fapi\/(.*)/, function(req, res) {
    return new fapi.Fapi(FAPI_FILES_ROOT).get(req, res, req.params[0]);
  });

  app.post(/^\/fapi\/(.*)/, function(req, res) {
    return new fapi.Fapi(FAPI_FILES_ROOT).post(req, res, req.params[0]);
  });

  app.get('/fapi', function(req, res) {
    return res.redirect('/fapi/');
  });

  port = process.env.PORT || 3000;

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
